insert into PartitionPlan (PARTITIONPLAN, DEFAULTSTORAGETIME, DEFAULTPARTITIONSIZE, MAXSTORAGETIME, PARTITIONTYPE) values ('medium_raw', 14, 48, 14, 1);
insert into PartitionPlan (PARTITIONPLAN, DEFAULTSTORAGETIME, DEFAULTPARTITIONSIZE, MAXSTORAGETIME, PARTITIONTYPE) values ('large_raw', 14, 48, 14, 0);
insert into PartitionPlan (PARTITIONPLAN, DEFAULTSTORAGETIME, DEFAULTPARTITIONSIZE, MAXSTORAGETIME, PARTITIONTYPE) values ('large_DAY', 14, 48, 14, 1);
insert into PartitionPlan (PARTITIONPLAN, DEFAULTSTORAGETIME, DEFAULTPARTITIONSIZE, MAXSTORAGETIME, PARTITIONTYPE) values ('medium_15MIN', 14, 48, 14, 1);

