


insert into TPActivation (TECHPACK_NAME, STATUS, VERSIONID, TYPE, MODIFIED) values ('DC_E_SASN', 'ACTIVE', 'DC_E_SASN:((14))', 'PM', 0);

insert into TypeActivation (TECHPACK_NAME, STATUS, TYPENAME, TABLELEVEL, STORAGETIME, TYPE, PARTITIONPLAN) values ('DC_E_SASN', 'ACTIVE', 'DC_E_SASN_TCP_CHARGING', 'DAY', -1, 'Measurement', 'extrasmall_day');
insert into TypeActivation (TECHPACK_NAME, STATUS, TYPENAME, TABLELEVEL, STORAGETIME, TYPE, PARTITIONPLAN) values ('DC_E_SASN', 'ACTIVE', 'DC_E_SASN_TCP_CHARGING', 'COUNT', -1, 'Measurement', 'extrasmall_count');
insert into TypeActivation (TECHPACK_NAME, STATUS, TYPENAME, TABLELEVEL, STORAGETIME, TYPE, PARTITIONPLAN) values ('DC_E_SASN', 'ACTIVE', 'DC_E_SASN_TCP_CHARGING', 'RAW', -1, 'Measurement', 'extrasmall_raw');

insert into DWHType (TECHPACK_NAME, TYPENAME, TABLELEVEL, STORAGEID, PARTITIONSIZE, PARTITIONCOUNT, STATUS, TYPE, OWNER, VIEWTEMPLATE, CREATETEMPLATE, NEXTPARTITIONTIME, BASETABLENAME, DATADATECOLUMN, PUBLICVIEWTEMPLATE, PARTITIONPLAN) values ('DC_E_SASN', 'DC_E_SASN_TCP_CHARGING', 'DAY', 'DC_E_SASN_TCP_CHARGING:DAY', -1, 3, 'ENABLED', 'PARTITIONED', 'dc', 'createview.vm', 'createpartition.vm', '2011-05-17 00:00:00', 'DC_E_SASN_TCP_CHARGING_DAY', 'DATE_ID', 'createpublicview.vm', 'extrasmall_day');
insert into DWHType (TECHPACK_NAME, TYPENAME, TABLELEVEL, STORAGEID, PARTITIONSIZE, PARTITIONCOUNT, STATUS, TYPE, OWNER, VIEWTEMPLATE, CREATETEMPLATE, NEXTPARTITIONTIME, BASETABLENAME, DATADATECOLUMN, PUBLICVIEWTEMPLATE, PARTITIONPLAN) values ('DC_E_SASN', 'DC_E_SASN_TCP_CHARGING', 'COUNT', 'DC_E_SASN_TCP_CHARGING:COUNT', -1, 3, 'ENABLED', 'PARTITIONED', 'dc', 'createview.vm', 'createpartition.vm', '2011-04-25 00:00:00', 'DC_E_SASN_TCP_CHARGING_COUNT', 'DATE_ID', 'createpublicview.vm', 'extrasmall_count');
insert into DWHType (TECHPACK_NAME, TYPENAME, TABLELEVEL, STORAGEID, PARTITIONSIZE, PARTITIONCOUNT, STATUS, TYPE, OWNER, VIEWTEMPLATE, CREATETEMPLATE, NEXTPARTITIONTIME, BASETABLENAME, DATADATECOLUMN, PUBLICVIEWTEMPLATE, PARTITIONPLAN) values ('DC_E_SASN', 'DC_E_SASN_TCP_CHARGING', 'RAW', 'DC_E_SASN_TCP_CHARGING:RAW', -1, 3, 'ENABLED', 'PARTITIONED', 'dc', 'createview.vm', 'createpartition.vm', '2011-04-23 01:00:00', 'DC_E_SASN_TCP_CHARGING_RAW', 'DATE_ID', 'createpublicview.vm', 'extrasmall_raw');

insert into DWHPartition (STORAGEID, TABLENAME, STARTTIME, ENDTIME, STATUS) values ('DC_E_SASN_TCP_CHARGING:COUNT', 'DC_E_SASN_TCP_CHARGING_COUNT_01', '2011-02-22 00:00:00', '2011-03-25 00:00:00', 'ACTIVE');
insert into DWHPartition (STORAGEID, TABLENAME, STARTTIME, ENDTIME, STATUS) values ('DC_E_SASN_TCP_CHARGING:COUNT', 'DC_E_SASN_TCP_CHARGING_COUNT_02', '2011-01-22 00:00:00', '2011-02-22 00:00:00', 'ACTIVE');
insert into DWHPartition (STORAGEID, TABLENAME, STARTTIME, ENDTIME, STATUS) values ('DC_E_SASN_TCP_CHARGING:COUNT', 'DC_E_SASN_TCP_CHARGING_COUNT_03', '2011-03-25 00:00:00', '2011-04-25 00:00:00', 'ACTIVE');
insert into DWHPartition (STORAGEID, TABLENAME, STARTTIME, ENDTIME, STATUS) values ('DC_E_SASN_TCP_CHARGING:DAY', 'DC_E_SASN_TCP_CHARGING_DAY_01', '2010-04-11 00:00:00', '2011-05-17 00:00:00', 'ACTIVE');
insert into DWHPartition (STORAGEID, TABLENAME, STARTTIME, ENDTIME, STATUS) values ('DC_E_SASN_TCP_CHARGING:DAY', 'DC_E_SASN_TCP_CHARGING_DAY_02', '2009-03-06 00:00:00', '2010-04-11 00:00:00', 'ACTIVE');
insert into DWHPartition (STORAGEID, TABLENAME, STARTTIME, ENDTIME, STATUS) values ('DC_E_SASN_TCP_CHARGING:DAY', 'DC_E_SASN_TCP_CHARGING_DAY_03', '2008-01-30 00:00:00', '2009-03-06 00:00:00', 'ACTIVE');

insert into DWHPartition (STORAGEID, TABLENAME, STARTTIME, ENDTIME, STATUS) values ('DC_E_SASN_TCP_CHARGING:RAW', 'DC_E_SASN_TCP_CHARGING_RAW_01', '1923-01-01 00:00:00', '1924-12-31 00:00:00', 'ACTIVE');
-- No end time
insert into DWHPartition (STORAGEID, TABLENAME, STARTTIME, STATUS) values ('DC_E_SASN_TCP_CHARGING:RAW', 'DC_E_SASN_TCP_CHARGING_RAW_02', '2011-01-01 00:00:00', 'ACTIVE');
insert into DWHPartition (STORAGEID, TABLENAME, STARTTIME, ENDTIME, STATUS) values ('DC_E_SASN_TCP_CHARGING:RAW', 'DC_E_SASN_TCP_CHARGING_RAW_03', '2099-01-01 00:00:00', '2099-12-31 00:00:00', 'ACTIVE');
-- no starttime, physical table cache will not use this entry
insert into DWHPartition (STORAGEID, TABLENAME, ENDTIME, STATUS) values ('DC_E_SASN_TCP_CHARGING:RAW', 'DC_E_SASN_TCP_CHARGING_RAW_04', '2099-12-31 00:00:00', 'ACTIVE');

insert into PartitionPlan (PARTITIONPLAN, DEFAULTSTORAGETIME, DEFAULTPARTITIONSIZE, MAXSTORAGETIME) values ('extrasmall_count', 30, 744, 90);
insert into PartitionPlan (PARTITIONPLAN, DEFAULTSTORAGETIME, DEFAULTPARTITIONSIZE, MAXSTORAGETIME) values ('extrasmall_day', 400, 9624, 1095);
insert into PartitionPlan (PARTITIONPLAN, DEFAULTSTORAGETIME, DEFAULTPARTITIONSIZE, MAXSTORAGETIME) values ('extrasmall_daybh', 400, 9624, 1095);
insert into PartitionPlan (PARTITIONPLAN, DEFAULTSTORAGETIME, DEFAULTPARTITIONSIZE, MAXSTORAGETIME) values ('extrasmall_plain', 90, 384, 250);
insert into PartitionPlan (PARTITIONPLAN, DEFAULTSTORAGETIME, DEFAULTPARTITIONSIZE, MAXSTORAGETIME) values ('extrasmall_rankbh', 400, 9624, 1095);
insert into PartitionPlan (PARTITIONPLAN, DEFAULTSTORAGETIME, DEFAULTPARTITIONSIZE, MAXSTORAGETIME) values ('extrasmall_raw', 30, 744, 90);
