CREATE TABLE META_DATABASES (USERNAME VARCHAR(30), VERSION_NUMBER VARCHAR(32), TYPE_NAME VARCHAR(15), CONNECTION_ID NUMERIC(40), CONNECTION_NAME VARCHAR(30), CONNECTION_STRING VARCHAR(200), PASSWORD VARCHAR(30), DESCRIPTION VARCHAR(32000), DRIVER_NAME VARCHAR(100), DB_LINK_NAME VARCHAR(128));
CREATE TABLE DATAFORMAT (DATAFORMATID VARCHAR(100), TYPEID VARCHAR(255), VERSIONID VARCHAR(128), OBJECTTYPE VARCHAR(255), FOLDERNAME VARCHAR(50), DATAFORMATTYPE VARCHAR(50));
CREATE TABLE DATAINTERFACE (INTERFACENAME VARCHAR(50), STATUS NUMERIC(40), INTERFACETYPE VARCHAR(50), DESCRIPTION VARCHAR(32000), DATAFORMATTYPE VARCHAR(50), INTERFACEVERSION VARCHAR(32), LOCKEDBY VARCHAR(255), LOCKDATE TIMESTAMP, PRODUCTNUMBER VARCHAR(255), ENIQ_LEVEL VARCHAR(12), RSTATE VARCHAR(255));
CREATE TABLE INTERFACEMEASUREMENT (
TAGID VARCHAR (50),    
DATAFORMATID      VARCHAR     (100),   
INTERFACENAME     VARCHAR     (50),    
TRANSFORMERID     VARCHAR     (255),   
STATUS            NUMERIC     (11),    
MODIFTIME         TIMESTAMP,    
DESCRIPTION       VARCHAR (32000), 
TECHPACKVERSION   VARCHAR     (32),    
INTERFACEVERSION  VARCHAR     (32));   

CREATE TABLE REFERENCECOLUMN (
TYPEID             VARCHAR(255),    
DATANAME           VARCHAR(128),   
COLNUMBER          NUMERIC(11),    
DATATYPE           VARCHAR(50),    
DATASIZE           INTEGER,    
DATASCALE          INTEGER,    
UNIQUEVALUE        NUMERIC(11),    
NULLABLE           INTEGER,    
INDEXES            VARCHAR(20),    
UNIQUEKEY          INTEGER,    
INCLUDESQL         INTEGER,    
INCLUDEUPD         INTEGER,    
COLTYPE            VARCHAR(16),    
DESCRIPTION        VARCHAR(32000), 
UNIVERSECLASS      VARCHAR(35),    
UNIVERSEOBJECT     VARCHAR(128),   
UNIVERSECONDITION  VARCHAR(255),   
DATAID             VARCHAR(255),   
BASEDEF            INTEGER);   

CREATE TABLE MEASUREMENTCOUNTER (
TYPEID           VARCHAR(255),      
DATANAME         VARCHAR(128),      
DESCRIPTION      VARCHAR(32000),
TIMEAGGREGATION  VARCHAR(50),       
GROUPAGGREGATION VARCHAR(50),       
COUNTAGGREGATION VARCHAR(50),       
COLNUMBER        NUMERIC(11),       
DATATYPE         VARCHAR(50),       
DATASIZE         INTEGER,       
DATASCALE        INTEGER,       
INCLUDESQL       INTEGER,       
UNIVOBJECT       VARCHAR(128),      
UNIVCLASS        VARCHAR(35),       
COUNTERTYPE      VARCHAR(16),       
COUNTERPROCESS   VARCHAR(16),       
DATAID           VARCHAR(255),      
FOLLOWJOHN       INTEGER);    

CREATE TABLE DATAITEM (
DATAFORMATID          VARCHAR(100),
DATANAME              VARCHAR(128),
COLNUMBER             NUMERIC(11),
DATAID                VARCHAR(255),
PROCESS_INSTRUCTION   VARCHAR(128),
DATATYPE              VARCHAR(50), 
DATASIZE              INTEGER, 
DATASCALE             INTEGER); 