CREATE TABLE META_DATABASES (
	USERNAME VARCHAR(30),
	VERSION_NUMBER VARCHAR(32),
	TYPE_NAME VARCHAR(15),
	CONNECTION_ID NUMERIC(38),
	CONNECTION_NAME VARCHAR(30),
	CONNECTION_STRING VARCHAR(200),
	PASSWORD VARCHAR(30),
	DESCRIPTION VARCHAR(32000),
	DRIVER_NAME VARCHAR(100),
	DB_LINK_NAME VARCHAR(128)
);

CREATE TABLE LOG_AGGREGATIONRULES (
  AGGREGATION	varchar(255),
  RULEID	int,
  TARGET_TYPE	varchar(50),
  TARGET_LEVEL	varchar(50),
  TARGET_TABLE	varchar(255),
  SOURCE_TYPE	varchar(50),
  SOURCE_LEVEL	varchar(50),
  SOURCE_TABLE	varchar(255),
  RULETYPE	varchar(50),
  AGGREGATIONSCOPE	varchar(50),
  STATUS	varchar(50),
  MODIFIED	timestamp,
  BHTYPE	varchar(50)
);
