--insert into Meta_databases (USERNAME, VERSION_NUMBER, TYPE_NAME, CONNECTION_ID, CONNECTION_NAME, CONNECTION_STRING, PASSWORD, DESCRIPTION, DRIVER_NAME) values ('SA', '0', 'USER', '0', 'etlrep', 'jdbc:hsqldb:mem:testdb', '', 'ETL Repository Database', 'org.hsqldb.jdbcDriver');
--insert into Meta_databases (USERNAME, VERSION_NUMBER, TYPE_NAME, CONNECTION_ID, CONNECTION_NAME, CONNECTION_STRING, PASSWORD, DESCRIPTION, DRIVER_NAME) values ('SA', '0', 'USER', '1', 'dwhrep', 'jdbc:hsqldb:mem:testdb', '', 'DWH Repository Database', 'org.hsqldb.jdbcDriver');
insert into Meta_databases (USERNAME, VERSION_NUMBER, TYPE_NAME, CONNECTION_ID, CONNECTION_NAME, CONNECTION_STRING, PASSWORD, DESCRIPTION, DRIVER_NAME) values ('SA', '0', 'USER', '2', 'dwh', 'jdbc:hsqldb:mem:testdb', '', 'The DataWareHouse Database', 'org.hsqldb.jdbcDriver');
--insert into Meta_databases (USERNAME, VERSION_NUMBER, TYPE_NAME, CONNECTION_ID, CONNECTION_NAME, CONNECTION_STRING, PASSWORD, DESCRIPTION, DRIVER_NAME) values ('SA', '0', 'DBA', '3', 'etlrep', 'jdbc:hsqldb:mem:testdb', '', 'ETL Repository Database', 'org.hsqldb.jdbcDriver');
--insert into Meta_databases (USERNAME, VERSION_NUMBER, TYPE_NAME, CONNECTION_ID, CONNECTION_NAME, CONNECTION_STRING, PASSWORD, DESCRIPTION, DRIVER_NAME) values ('SA', '0', 'DBA', '4', 'dwhrep', 'jdbc:hsqldb:mem:testdb', '', 'DWH Repository Database', 'org.hsqldb.jdbcDriver');
--insert into Meta_databases (USERNAME, VERSION_NUMBER, TYPE_NAME, CONNECTION_ID, CONNECTION_NAME, CONNECTION_STRING, PASSWORD, DESCRIPTION, DRIVER_NAME) values ('SA', '0', 'DBA', '5', 'dwh', 'jdbc:hsqldb:mem:testdb', '', 'The DataWareHouse Database', 'org.hsqldb.jdbcDriver');


insert into LOG_AGGREGATIONRULES (AGGREGATION, RULEID, TARGET_TYPE, TARGET_LEVEL, TARGET_TABLE, SOURCE_TYPE, SOURCE_LEVEL, SOURCE_TABLE, RULETYPE, AGGREGATIONSCOPE, STATUS, MODIFIED, BHTYPE) values ('DC_E_IMS_IPW_AAA_COUNT', 1, 'DC_E_IMS_IPW_AAA', 'COUNT', 'DC_E_IMS_IPW_AAA_COUNT', 'DC_E_IMS_IPW_AAA', 'RAW', 'DC_E_IMS_IPW_AAA_RAW', 'COUNT', 'DAY', '', null, '');
insert into LOG_AGGREGATIONRULES (AGGREGATION, RULEID, TARGET_TYPE, TARGET_LEVEL, TARGET_TABLE, SOURCE_TYPE, SOURCE_LEVEL, SOURCE_TABLE, RULETYPE, AGGREGATIONSCOPE, STATUS, MODIFIED, BHTYPE) values ('DC_E_IMS_IPW_AAA_DAY', 0, 'DC_E_IMS_IPW_AAA', 'DAY', 'DC_E_IMS_IPW_AAA_DAY', 'DC_E_IMS_IPW_AAA', 'COUNT', 'DC_E_IMS_IPW_AAA_COUNT', 'TOTAL', 'DAY', '', null, '');
