ALTER TABLE MZTechPacks MODIFY TECHPACK_VERSION NOT NULL;
ALTER TABLE MZTechPacks DROP PRIMARY KEY;
ALTER TABLE MZTechPacks ADD CONSTRAINT VERSIONID_TECHPACK_VERSION PRIMARY KEY (VERSIONID,TECHPACK_VERSION);