ALTER TABLE META_TRANSFER_ACTIONS RENAME WHERE_CLAUSE TO WHERE_CLAUSE_01;
ALTER TABLE META_TRANSFER_ACTIONS RENAME ACTION_CONTENTS TO ACTION_CONTENTS_01;

ALTER TABLE META_TRANSFER_ACTIONS ADD WHERE_CLAUSE_02 varchar(32000) NULL;
ALTER TABLE META_TRANSFER_ACTIONS ADD WHERE_CLAUSE_03 varchar(32000) NULL;
ALTER TABLE META_TRANSFER_ACTIONS ADD ACTION_CONTENTS_02 varchar(32000) NULL;
ALTER TABLE META_TRANSFER_ACTIONS ADD ACTION_CONTENTS_03 varchar(32000) NULL;