insert into GROUPTYPES (GROUPTYPE, VERSIONID, DATANAME, DATATYPE, DATASIZE, DATASCALE, NULLABLE) values ('APN', 'EVENT_E_SGEH:((42))', 'APN', 'varchar', '127', '0', 1);
insert into GROUPTYPES (GROUPTYPE, VERSIONID, DATANAME, DATATYPE, DATASIZE, DATASCALE, NULLABLE) values ('IMSI', 'EVENT_E_SGEH:((42))', 'IMSI', 'unsigned bigint', '0', '0', 1);
insert into GROUPTYPES (GROUPTYPE, VERSIONID, DATANAME, DATATYPE, DATASIZE, DATASCALE, NULLABLE) values ('TAC', 'EVENT_E_SGEH:((42))', 'TAC', 'unsigned int', '0', '0', 1);
insert into GROUPTYPES (GROUPTYPE, VERSIONID, DATANAME, DATATYPE, DATASIZE, DATASCALE, NULLABLE) values ('MCC_MNC', 'EVENT_E_SGEH:((42))', 'MCC', 'unsigned int', '0', '0', 1);
insert into GROUPTYPES (GROUPTYPE, VERSIONID, DATANAME, DATATYPE, DATASIZE, DATASCALE, NULLABLE) values ('MCC_MNC', 'EVENT_E_SGEH:((42))', 'MNC', 'unsigned int', '0', '0', 1);
