CREATE TABLE DataFormat (
	DATAFORMATID VARCHAR(100),
	TYPEID VARCHAR(255),
	VERSIONID VARCHAR(128),
	OBJECTTYPE VARCHAR(255),
	FOLDERNAME VARCHAR(128),
	DATAFORMATTYPE VARCHAR(50)
);
CREATE TABLE DataInterface (
	INTERFACENAME VARCHAR(255),
	STATUS NUMERIC(9),
	INTERFACETYPE VARCHAR(50),
	DESCRIPTION VARCHAR(32000),
	DATAFORMATTYPE VARCHAR(50),
	INTERFACEVERSION VARCHAR(32),
	LOCKEDBY VARCHAR(255),
	LOCKDATE TIMESTAMP,
	PRODUCTNUMBER VARCHAR(255),
	ENIQ_LEVEL VARCHAR(12),
	RSTATE VARCHAR(255),
	INSTALLDESCRIPTION VARCHAR(32000)
);
CREATE TABLE DataItem (
	DATAFORMATID VARCHAR(100),
	DATANAME VARCHAR(128),
	COLNUMBER NUMERIC(9),
	DATAID VARCHAR(255),
	PROCESS_INSTRUCTION VARCHAR(128),
	DATATYPE VARCHAR(50),
	DATASIZE INTEGER,
	DATASCALE INTEGER
);
CREATE TABLE InterfaceMeasurement (
	TAGID VARCHAR(128),
	DATAFORMATID VARCHAR(100),
	INTERFACENAME VARCHAR(255),
	TRANSFORMERID VARCHAR(255),
	STATUS NUMERIC(9),
	MODIFTIME TIMESTAMP,
	DESCRIPTION VARCHAR(32000),
	TECHPACKVERSION VARCHAR(32),
	INTERFACEVERSION VARCHAR(32)
);
CREATE TABLE TPActivation (
	TECHPACK_NAME VARCHAR(30),
	STATUS VARCHAR(10),
	VERSIONID VARCHAR(128),
	TYPE VARCHAR(10),
	MODIFIED INTEGER
);
CREATE TABLE MeasurementCounter (
	TYPEID VARCHAR(255),
	DATANAME VARCHAR(128),
	DESCRIPTION VARCHAR(32000),
	TIMEAGGREGATION VARCHAR(50),
	GROUPAGGREGATION VARCHAR(50),
	COUNTAGGREGATION VARCHAR(32000),
	COLNUMBER NUMERIC(9),
	DATATYPE VARCHAR(50),
	DATASIZE INTEGER,
	DATASCALE INTEGER,
	INCLUDESQL INTEGER,
	UNIVOBJECT VARCHAR(128),
	UNIVCLASS VARCHAR(35),
	COUNTERTYPE VARCHAR(16),
	COUNTERPROCESS VARCHAR(16),
	DATAID VARCHAR(255),
	FOLLOWJOHN INTEGER
);
CREATE TABLE ReferenceColumn (
	TYPEID VARCHAR(255),
	DATANAME VARCHAR(128),
	COLNUMBER NUMERIC(9),
	DATATYPE VARCHAR(50),
	DATASIZE INTEGER,
	DATASCALE INTEGER,
	UNIQUEVALUE NUMERIC(9),
	NULLABLE INTEGER,
	INDEXES VARCHAR(20),
	UNIQUEKEY INTEGER,
	INCLUDESQL INTEGER,
	INCLUDEUPD INTEGER,
	COLTYPE VARCHAR(16),
	DESCRIPTION VARCHAR(32000),
	UNIVERSECLASS VARCHAR(35),
	UNIVERSEOBJECT VARCHAR(128),
	UNIVERSECONDITION VARCHAR(255),
	DATAID VARCHAR(255),
	BASEDEF INTEGER
);
CREATE TABLE META_DATABASES (
	USERNAME VARCHAR(30),
	VERSION_NUMBER VARCHAR(32),
	TYPE_NAME VARCHAR(15),
	CONNECTION_ID NUMERIC(31),
	CONNECTION_NAME VARCHAR(30),
	CONNECTION_STRING VARCHAR(400),
	PASSWORD VARCHAR(30),
	DESCRIPTION VARCHAR(32000),
	DRIVER_NAME VARCHAR(100),
	DB_LINK_NAME VARCHAR(128)
);
